services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skinmatch-backend
    ports:
      - "4001:4001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: skinmatch-redis
    ports:
      - "6379:6379"
